language: rust
sudo: false
dist: trusty

rust:
    - nightly
    - beta
    - stable

env:
    -
    - CARGO_CFG_HTTPARSE_DISABLE_SIMD=1
    - CARGO_CFG_HTTPARSE_DISABLE_SIMD_COMPILETIME=1 RUSTFLAGS="-C target_feature=+avx2"
    - CARGO_CFG_HTTPARSE_DISABLE_SIMD_COMPILETIME=1 RUSTFLAGS="-C target_feature=+sse4.2"
    - CARGO_CFG_HTTPARSE_DISABLE_SIMD_COMPILETIME=1 RUSTFLAGS="-C target_feature=+sse4.2,+avx2"
    - RUSTFLAGS="-C target_feature=+sse4.2"
    - RUSTFLAGS="-C target_feature=+avx2"
    - RUSTFLAGS="-C target_feature=+sse4.2,+avx2"

matrix:
    fast_finish: true
    include:
        - rust: 1.10.0 # minimum Rust version

script:
    - cargo build --no-default-features
    - 'if [ "$TRAVIS_RUST_VERSION" != "1.10.0" ]; then cargo test --no-default-features; fi'
    - cargo build
    - 'if [ "$TRAVIS_RUST_VERSION" != "1.10.0" ]; then cargo test; fi'

