language: rust
sudo: false
dist: trusty

rust:
    - nightly
    - beta
    - stable
    - 1.10.0

env:
    - CARGO_CFG_HTTPARSE_DISABLE_SIMD=1
    - CARGO_CFG_HTTPARSE_DISABLE_SIMD_COMPILETIME=1
    -

matrix:
    fast_finish: true

script:
    - cargo build --no-default-features
    - 'if [ "$TRAVIS_RUST_VERSION" != "1.10.0" ]; then cargo test --no-default-features; fi'
    - cargo build
    - 'if [ "$TRAVIS_RUST_VERSION" != "1.10.0" ]; then cargo test; fi'

