[package]

name = "httparse"
version = "0.1.4"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT"
description = "A tiny, safe, speedy HTTP/1.x parser."
repository = "https://github.com/seanmonstar/httparse"

[dev-dependencies]
pico-sys = "*"
