[package]

name = "httparse"
version = "0.0.3"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT"
description = "A tiny, safe, speedy HTTP/1.x parser."

[dev-dependencies]
pico-sys = "*"
